name: demo-action

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4

     - name: run a sample action
       run: echo Hello world
