name: demo-action

on:
  push:
    branches: main
    
  issues:
      types: opened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - name: run a sample action
       run: echo Hello world

     - name: my-artifacts
       uses: actions/upload-artifact@v4
       with:
         name: build artifacts
         path: $({github.workspace})
  deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
       - name: Download artifacts
         uses: actions/download-artifact@v4
         with:
           name: my-artifacts
           run: ls -R
